#!/bin/bash

echo "🎯 DogeGPU 51% Attack Environment"
echo "=================================="
echo "Educational purposes only!"
echo ""

# Check if nodes are already running
if pgrep -f "dogpud" > /dev/null; then
    echo "⚠️  DogeGPU nodes are already running!"
    echo "Kill them first with: pkill -f dogpud"
    echo ""
fi

echo "📋 Available Commands:"
echo "====================="
echo ""
echo "🟢 Network Setup:"
echo "  ./start_honest.sh     - Start honest network node"
echo "  ./start_victim.sh     - Start victim node"
echo "  ./start_attack.sh     - Start your attack node"
echo ""
echo "💀 Attack Execution:"
echo "  ./double_spend_attack.sh           - Simple double spend"
echo "  python3 advanced_attack_tools.py   - Advanced attack suite"
echo ""
echo "🔍 Monitoring:"
echo "  ./check_nodes.sh      - Check all node status"
echo ""
echo "📖 Documentation:"
echo "  cat ATTACK_GUIDE.md   - Complete attack guide"
echo ""
echo "🎯 Quick Start (3 terminals needed):"
echo "====================================="
echo "Terminal 1: ./start_honest.sh"
echo "Terminal 2: ./start_victim.sh" 
echo "Terminal 3: ./start_attack.sh"
echo ""
echo "Then connect your rented hashpower to: YOUR_SERVER_IP:8335"
echo "Current network: Block 1861257, 970MH/s hashrate"
echo ""
echo "🚀 Ready to attack your test blockchain!"
echo "Remember: This is educational - use responsibly!"